name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies including dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]  # Installs package + dev dependencies (like ruff, pytest)
          pip install build twine # Still need build and twine for publishing steps

      - name: Check formatting with Ruff
        run: ruff format --check .

      - name: Lint with Ruff
        run: ruff check .

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
